version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: crazycat836/minecraftrobot:latest
    container_name: minecraft-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - MC_SERVER_NAME=${MC_SERVER_NAME}
      - MC_SERVER_VERSION=${MC_SERVER_VERSION}
      - MC_SERVER_IP=${MC_SERVER_IP}
      - MC_SERVER_PORT=${MC_SERVER_PORT:-25565}
      - MC_SERVER_TYPE=${MC_SERVER_TYPE:-java}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 